#!/bin/bash

apk update && apk upgrade 
apk add nodejs npm perl python3 py3-pip net-tools docker docker-compose
echo "Node Version $(node -v)"

startWebService() {
    cd /www
    npm i
    bash /scriptservice/serverarc
};
startPyService() {
    cd /scriptservice/python/
    bash pyarc
    
}


executeServer() {
    startWebService;
    startPyService;
}






executeServer