#!/bin/bash
printf "Updating repos...\n"
apk update && apk upgrade
apk add nodejs npm perl python3 py3-pip net-tools py3-cryptography py3-requests py3-paramiko py3-setuptools
echo "Node Version $(node -v)"

startWebService() {
    cd /www
    npm i
    bash /scriptservice/serverarc
};
startPyService() {
    cd /scriptservice/python/
    bash /scriptservice/pyarc
    
}


executeServer() {
    startPyService;

    if ! [ -f /env/no-web ]; then
            startWebService;
    fi

}






executeServer