
version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  flutter: circleci/flutter@1.1.0
  node: circleci/node@5.1.0


jobs:
  buildMain:

    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - docker/install-docker
      - flutter/install_sdk

      - run:
          name: "build"
          command: "npm build"

workflows:
  buildMain-workflow:
    jobs:
      - buildMain
      
