#!/bin/bash

startWebService() {
    bash /scriptservice/serverarc
};
startPyService() {
    cd /scriptservice/python/
    bash /scriptservice/pyarc
    
}


executeServer() {
    startPyService;

    if [ "$web" = "true" ]; then
            startWebService;
    fi;

}






executeServer