#!/bin/bash
cd /www

if [ -n "$port" ]  &&  [ "$port" -eq "$port" ] 2>/dev/null; then
  echo Running webserver on port $port 
else
  echo Running webserver on port 6721
  echo Port $port not a number | tee -a /var/log/Chameleon.log
fi
python3 webserver >> /dev/null 2>&1