#!/bin/bash
if [ $UID = 0 ]  ||  [ $EUID = 0 ]  ||  [ $(id -u) = 0 ] || [ $USER = "root" ]; then
    su  chameleon
    echo "Please don't run as root"  >> /dev/stderr
fi
startWebService() {
    bash /scriptservice/serverarc
};
startPyService() {
    cd /scriptservice/python/
    bash /scriptservice/pyarc
    
}


executeServer() {
    startPyService;

    if [ "$web" = "true" ]; then
            startWebService;
    fi;

}






executeServer