#!/bin/bash
if [ $(whoami) = "root" ] || [ $(id -u) = 0 ]; then
    su  chameleon
    echo "Please don't run as root"  >> /dev/stderr
fi
startWebService() {
    bash /scriptservice/serverarc
};
startPyService() {
    cd /scriptservice/python/
    bash /scriptservice/pyarc
    
}


executeServer() {
    startPyService;

    if [ "$web" = "true" ]; then
            startWebService;
    fi;

}






executeServer